repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
        name: Ruff Format (Python)
        files: ^(app|tests)/.*\.py$
      - id: ruff
        name: Ruff Lint (Python)
        files: ^(app|tests)/.*\.py$
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: Mypy (types)
        files: ^app/.*\.py$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: Bandit (security)
        args: ["-q", "-r", "app"]
        files: ^app/.*\.py$

  - repo: local
    hooks:
      - id: eslint-frontend
        name: ESLint (frontend)
        language: system
        entry: bash
        args:
          - -lc
          - >-
            cd frontend && if [ -d node_modules ]; then npm run lint; else echo '[eslint]
            Skipping: node_modules not installed'; fi
        files: ^frontend/src/.*\.(ts|tsx)$
        pass_filenames: false
