#repos:
#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.13.0
#    hooks:
#      - id: ruff-format
#        name: Ruff Format (Python)
#        files: ^(postfix_blocker|tests)/.*\.py$
#      - id: ruff
#        name: Ruff Lint (Python)
#        files: ^(postfix_blocker|tests)/.*\.py$
#        args: ["--fix"]
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.18.1
#    hooks:
#      - id: mypy
#        name: Mypy (types)
#        files: ^postfix_blocker/.*\.py$
#
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.8.6
#    hooks:
#      - id: bandit
#        name: Bandit (security)
#        args: ["-q", "-r", "postfix_blocker"]
#        files: ^postfix_blocker/.*\.py$
#
#  - repo: local
#    hooks:
#      - id: eslint-frontend
#        name: ESLint (frontend, --fix)
#        language: system
#        entry: bash
#        args:
#          - -lc
#          - >-
#            cd frontend && if [ -d node_modules ]; then (npm run lint:fix || npm run lint);
#            else echo '[eslint] Skipping: node_modules not installed'; fi
#        files: ^frontend/src/.*\.(ts|tsx)$
#        pass_filenames: false
