services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: blocker
      POSTGRES_PASSWORD: blocker
      POSTGRES_DB: blocker
    ports:
      - "5432:5432"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  postfix:
    build:
      context: .
      dockerfile: docker/postfix/Dockerfile
    ports:
      - "1025:25"
      - "5000:5000"
    depends_on:
      - db
      - mailhog
    environment:
      BLOCKER_DB_URL: postgresql://blocker:blocker@db:5432/blocker
