-- IBM Db2 (LUW) initialization script for postfix-blocker
-- Creates required tables and triggers to maintain update timestamps.

-- Note: Db2 does not support IF NOT EXISTS for CREATE TABLE in all versions.
-- Run this on a clean database or drop existing objects manually before applying.

-- Table: BLOCKED_ADDRESSES
CREATE TABLE BLOCKED_ADDRESSES (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    PATTERN VARCHAR(255) NOT NULL,
    IS_REGEX SMALLINT NOT NULL DEFAULT 0,
    TEST_MODE SMALLINT NOT NULL DEFAULT 1,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);

-- Table: CRIS_PROPS
CREATE TABLE CRISOP.CRIS_PROPS
(
    KEY VARCHAR(1024 OCTETS) not null
        CONSTRAINT XPKCRISPROPS
            PRIMARY KEY,
    VALUE VARCHAR(1024 OCTETS),
    UPDATE_TS TIMESTAMP(6)
);

-- Trigger: maintain UPDATED_AT on update of BLOCKED_ADDRESSES
CREATE OR REPLACE TRIGGER TRG_BLOCKED_ADDRESSES_SET_UPDATED
NO CASCADE BEFORE UPDATE ON BLOCKED_ADDRESSES
REFERENCING NEW AS N
FOR EACH ROW
SET N.UPDATED_AT = CURRENT TIMESTAMP;


