-- PostgreSQL initialization script for postfix-blocker
-- Creates required tables and minimal triggers to maintain update timestamps.

-- Table: blocked_addresses
CREATE TABLE IF NOT EXISTS blocked_addresses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    is_regex BOOLEAN NOT NULL DEFAULT FALSE,
    test_mode BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: cris_props
CREATE TABLE IF NOT EXISTS cris_props (
    key VARCHAR(1024) PRIMARY KEY,
    value VARCHAR(1024),
    update_ts TIMESTAMP WITHOUT TIME ZONE
);

-- Trigger function to set updated_at on UPDATE for blocked_addresses
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- Triggers
DROP TRIGGER IF EXISTS trg_blocked_addresses_set_updated_at ON blocked_addresses;
CREATE TRIGGER trg_blocked_addresses_set_updated_at
BEFORE UPDATE ON blocked_addresses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

