name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.21'
          cache: 'pip'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Python and frontend deps
        run: |
          make install

      - name: Install Playwright browsers and system dependencies
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run unified CI (lint, build, tests; DB2-only)
        env:
          TEST_DB2_URL: ibm_db_sa://db2inst1:blockerpass@localhost:50000/BLOCKER
          BACKEND_WAIT_TIMEOUT_DB2: '900'
          SMTP_PORT_DB2: '1026'
          MAILHOG_HOST: 'localhost'
          MAILHOG_PORT: '8025'
        run: |
          make ci

      - name: Generate coverage badge endpoint
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          python scripts/gen_coverage_badge.py coverage.xml badges/coverage.json

      - name: Publish coverage badge to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: badges
          keep_files: true

      - name: Upload coverage artefacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            frontend/coverage/**/*.lcov
