name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Python and frontend deps
        run: |
          make install

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1

      - name: Run unified CI (lint, build, tests)
        env:
          TEST_PG_URL: postgresql://blocker:blocker@localhost:5433/blocker
          TEST_DB2_URL: ibm_db_sa://db2inst1:blockerpass@localhost:50000/BLOCKER
          BACKEND_WAIT_TIMEOUT_PG: '180'
          BACKEND_WAIT_TIMEOUT_DB2: '900'
          SMTP_PORT_PG: '1025'
          SMTP_PORT_DB2: '1026'
          MAILHOG_HOST: 'localhost'
          MAILHOG_PORT: '8025'
        run: |
          make ci
