name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.21'
          cache: 'pip'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Python and frontend deps
        run: |
          make install

      - name: Install Playwright browsers and system dependencies
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run unified CI (lint, build, tests)
        env:
          TEST_PG_URL: postgresql://blocker:blocker@localhost:5433/blocker
          TEST_DB2_URL: ibm_db_sa://db2inst1:blockerpass@localhost:50000/BLOCKER
          BACKEND_WAIT_TIMEOUT_PG: '180'
          BACKEND_WAIT_TIMEOUT_DB2: '900'
          SMTP_PORT_PG: '1025'
          SMTP_PORT_DB2: '1026'
          MAILHOG_HOST: 'localhost'
          MAILHOG_PORT: '8025'
        run: |
          make ci

      - name: Upload coverage artefacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            frontend/coverage/**/*.lcov
